spring:
  profiles:
    active: @profile.active@
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hutengqi1228.?
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数
      minimum-idle: 10
      # 连接池最大连接数
      maximum-pool-size: 1000
      connection-test-query: select 1
      # 空闲连接超时时间
      idle-timeout: 60000
      # 连接超时时间
      connection-timeout: 60000
  redis:
    host: localhost
    password: redispw
    port: 32768
    database: 7
    timeout: 5000
    lettuce:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
server:
  port: 8787
  servlet:
    context-path: /web
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: sincerity_producer