server:
  port: 8788


spring:
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
    datasource:
      name: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-sphere-00?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: hutengqi1228.?
        minimum-idle: 10
        maximum-pool-size: 1000
        connection-test-query: select 1
        idle-timeout: 60000
        connection-timeout: 60000
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-sphere-01?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: hutengqi1228.?
        minimum-idle: 10
        maximum-pool-size: 1000
        connection-test-query: select 1
        idle-timeout: 60000
        connection-timeout: 60000
    props:
      sql-show: true
    rules:
      sharding:
        tables:
          shoping:
            actual-data-nodes: ds$->{0..1}.shoping_00
            database-strategy:
              standard:
                sharding-column: shoping_id
                sharding-algorithm-name: database-inline
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{shoping_id % 2}
